### ISSUE TITLE
Support elasticsearch 1.x

### ISSUE THREAD

**Issue by danielpops** [duo-labs/cloudtracker#11]
The query language semantics are slightly different (e.g. `exists` in 1.x was a filter, in later versions it is a query. See http://www.dlxedu.com/askdetail/3/0620e1124992fb281da93c7efe53b97f.html and https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_query_dsl_changes.html)

**Comment by danielpops** [comment]
Now I realize that there are also probably some philosophical questions to be answered, such as should such old versions be supported, what to do about requirements.txt, etc. fwiw, I have some local changes that can make this tool work in my infrastructure. I'll send a PR out and let duo-labs deal with the philosophical side of things :)

**Comment by 0xdabbad00** [comment]
I am not interested in supporting 1.x, but I'm totally fine incorporating your changes if they work for my environment on 6.x without overly complicating things.  I don't expect a whole lot of future work for this tool to involve changes or additions to ElasticSearch queries, or if it does, it should be isolated to new functionality that you can avoid using until you make any fixes that may be needed.  I will not be testing future changes in a 1.x environment, but will attempt to be mindful of maintaining patterns you create that I can use for any new code that works for my environment and hopefully works for yours.

So please continue sending changes to support ES 1.x and I'll attempt to incorporate them and avoid breaking things moving forward, but because I won't be testing against a 1.x environment, you may still need to fix minor things in future updates.
